version: '3.5'

services:
    frontend:
        image: &image frontend1
        volumes: &volumes
            - ./:/bimcod
        entrypoint: &entrypoint sh
        command: -c "npm run dev"
        ports: 
            - 80:3000

    backend:
        image: d3
        volumes: &volumes
            - ./:/bimcod
        entrypoint: &entrypoint bash
        command: -c "npm run build && cd dist && live-server"
        ports: 
            - 8080:8080

    test:
        image: *image
        volumes: &volumes
            - ./:/bimcod
        entrypoint: ["tail", "-f", "/dev/null"]
        ports:
            - 8000:8000
            - 80:3000

