# Generated by Django 4.2.6 on 2023-10-16 12:59

import bimcod.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bimcod", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageproject",
            name="image",
            field=models.ImageField(
                unique=True, upload_to=bimcod.models.get_upload_path_project
            ),
        ),
    ]
