# Generated by Django 4.2.6 on 2023-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bimcod", "0007_alter_capitaltype_living_alter_capitaltype_prom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitaltype",
            name="living",
            field=models.FloatField(
                default=200.1, verbose_name="Коэффициент жилых зданий"
            ),
        ),
        migrations.AlterField(
            model_name="capitaltype",
            name="prom",
            field=models.FloatField(
                default=250.1,
                verbose_name="Коэффициент промышленные объектов и сооружений",
            ),
        ),
        migrations.AlterField(
            model_name="capitaltype",
            name="public",
            field=models.FloatField(
                default=100.1, verbose_name="Коэффициент общественных зданий"
            ),
        ),
    ]
