# Generated by Django 4.2.6 on 2023-12-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bimcod", "0013_alter_project_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        verbose_name='Выделенный текст. Выделенный текст вставить в формате <span class="highlight"><span>Выделенный текст</span></span>'
                    ),
                ),
                (
                    "order",
                    models.IntegerField(verbose_name="Номер карточки на странице"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="",
                        verbose_name="Фотография в карточке. Предпочтительное соотношение сторон 1 к 1",
                    ),
                ),
            ],
            options={"verbose_name_plural": 'Карточки на странице "О нас"',},
        ),
    ]
